### ISSUE TITLE
Incompatible with jupyterlab-0.11.2?

### ISSUE THREAD

**Issue by croth1** [dask/dask-labextension#13]
The current version seems to be incompatible with the latest version of jupyterlab.

I am getting:

```
Uncaught (in promise) Error: No provider for: jupyter.services.commandpalette.
    at JupyterLab.Application.resolveService (http://localhost:8890/lab/main.bundle.js:12831:36)
    at http://localhost:8890/lab/main.bundle.js:12793:73
    at Array.map (native)
    at JupyterLab.Application.activatePlugin (http://localhost:8890/lab/main.bundle.js:12793:39)
    at http://localhost:8890/lab/main.bundle.js:12879:67
    at Array.map (native)
    at JupyterLab.Application.start (http://localhost:8890/lab/main.bundle.js:12879:34)
    at JupyterLab.start (http://localhost:8890/lab/main.bundle.js:1292:40)
    at http://localhost:8890/lab:81:7
```

Installed dask-labextensions according to the README. Running jupyterlab=0.11.2 from conda-forge on MacOS Sierra.

**Comment by blink1073** [comment]
Hi @croth1, I opened #14 with the fix in the source.  We'll have to wait for @canavandl or @mrocklin to merge that and cut a release.

**Comment by blink1073** [comment]
In the future, if the version gets out of sync, it will no longer register as a valid `labextension` (under `jupyter labextension list`), and the application will still load without this plugin.

**Comment by blink1073** [comment]
(These changes were introduced by recent versions of the extension builder and JupyterLab).

**Comment by croth1** [comment]
@blink1073, thanks a lot 👍
