### ISSUE TITLE
Error:  Failed to list clusters: might the server extension not be installed/enabled?

### ISSUE THREAD

**Issue by willyyang** [dask/dask-labextension#214]
I'm running into the error `Failed to list clusters: might the server extension not be installed/enabled?` after I've ran the following steps and start up JupyterLab  in JupyterHub: 
```
pip install dask_labextension
jupyter labextension install dask-labextension
jupyter lab build --minimize=False --dev-build=False
```

I'm able to see `dask-labextension v5.1.0 enabled OK (python, dask_labextension)` on `jupyter labextension list` 

I've also tried following another comment from a similar error thread (https://github.com/dask/dask-labextension/issues/87#issuecomment-553630615) for enabling serverextension after the `jupyter lab build..` (didnt really expect this to work since I have jupyter notebook version > 5.2) which results in :

```
jupyter serveretension enable dask_labextension
Enabling: dask_labextension
- Writing config: /opt/app-root/src/.jupyter
   - Validating...
Error loading server extension dask_labextension
     is dask_labextension importable?
``` 

**Environment**:
os: Debian GNU/Linux 10 (buster)
python: 3.8.8

**installed via pip** 
dask: 2021.11.1
dask-labextension: 5.1.0
jupyterhub: 1.4.2

**jupyter --version**
jupyter core: 4.7.1
jupyter-notebook: 6.4.1
jupyter lab: 3.0.17

Thanks for any help or tips in advance.

**Comment by jacobtomlinson** [comment]
Are you able to open a Python prompt and run `dask_labextension`?

**Comment by willyyang** [comment]
@jacobtomlinson  seeing this error:

```
(2021-11-22 16:05:30) (~)

-$ pip list | grep dask

dask                               2021.11.1

dask-labextension                  5.1.0

 

(2021-11-22 16:05:37) (~)

-$ python

Python 3.8.8 (default, Apr 13 2021, 19:58:26)

[GCC 7.3.0] :: Anaconda, Inc. on linux

Type "help", "copyright", "credits" or "license" for more information.

>>> import dask_labextension

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/opt/conda/lib/python3.8/site-packages/dask_labextension/__init__.py", line 6, in <module>

    from .clusterhandler import DaskClusterHandler

  File "/opt/conda/lib/python3.8/site-packages/dask_labextension/clusterhandler.py", line 11, in <module>

    from .manager import manager

  File "/opt/conda/lib/python3.8/site-packages/dask_labextension/manager.py", line 12, in <module>

    from dask.distributed import Adaptive, utils

  File "/opt/conda/lib/python3.8/site-packages/dask/distributed.py", line 11, in <module>

    from distributed import *

  File "/opt/conda/lib/python3.8/site-packages/distributed/__init__.py", line 7, in <module>

    from .actor import Actor, ActorFuture

  File "/opt/conda/lib/python3.8/site-packages/distributed/actor.py", line 6, in <module>

    from .client import Future, default_client

  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 30, in <module>

    from dask.compatibility import apply

ImportError: cannot import name 'apply' from 'dask.compatibility' (/opt/conda/lib/python3.8/site-packages/dask/compatibility.py)
```

**Comment by willyyang** [comment]
Thanks that update worked to align the two package versions.

**Comment by jacobtomlinson** [comment]
Awesome. Strange that they managed to get out of sync, we usually hard pin them. Glad it's working for you.
