### ISSUE TITLE
ValueError: "dask-labextension" is not a valid npm package

### ISSUE THREAD

**Issue by randerzander** [dask/dask-labextension#215]
**What happened**:
With jupyter-lab version 3.2.5, I'm unable to install dask-labextension.

**What you expected to happen**:
I expected dask-labextension to be installed/enabled in JupyterLab.

**Minimal Complete Verifiable Example**:
```
~/shared/notebooks$ jupyter labextension install dask-labextension
An error occurred.
ValueError: "dask-labextension" is not a valid npm package
See the log file for details:  /tmp/jupyterlab-debug-ypgxw3sq.log
(dsql-12-15) rgelhausen@rl-dgx2-r13-u7-rapids-dgx201:~/shared/notebooks$ cat /tmp/jupyterlab-debug-ypgxw3sq.log 
Node v17.1.0

Yarn configuration loaded.
> /home/rgelhausen/conda/envs/dsql-12-15/bin/npm pack dask-labextension
npm ERR! code E503
npm ERR! 503 Service Unavailable - GET https://registry.npmjs.org/dask-labextension - Service Unavailable

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rgelhausen/.npm/_logs/2021-12-15T15_28_46_426Z-debug.log

Traceback (most recent call last):

  File "/home/rgelhausen/conda/envs/dsql-12-15/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield

  File "/home/rgelhausen/conda/envs/dsql-12-15/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 135, in start
    ans = self.run_task()

  File "/home/rgelhausen/conda/envs/dsql-12-15/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 174, in run_task
    return any([

  File "/home/rgelhausen/conda/envs/dsql-12-15/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 175, in <listcomp>
    install_extension(

  File "/home/rgelhausen/conda/envs/dsql-12-15/lib/python3.8/site-packages/jupyterlab/commands.py", line 411, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/home/rgelhausen/conda/envs/dsql-12-15/lib/python3.8/site-packages/jupyterlab/commands.py", line 634, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/home/rgelhausen/conda/envs/dsql-12-15/lib/python3.8/site-packages/jupyterlab/commands.py", line 1684, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "/home/rgelhausen/conda/envs/dsql-12-15/lib/python3.8/site-packages/jupyterlab/commands.py", line 1763, in _extract_package
    raise ValueError(msg % source)

ValueError: "dask-labextension" is not a valid npm package

Exiting application: lab
```
**Anything else we need to know?**:
N/A

**Environment**:
- Dask version: 2021.11.2
- Python version: 3.8
- Operating System: 
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
- Install method (conda, pip, source):
conda

**Comment by ian-r-rose** [comment]
Two things:
1. It looks like the error here was a hiccup in `npm`'s registry (see the 500 error in the traceback). This has likely been resolved.
1. It looks to me like you are using the pre-JupyterLab-3.0 way of installing extensions, can you try installing just from PyPI as described [here](https://github.com/dask/dask-labextension#jupyterlab-30-or-greater)?

**Comment by ian-r-rose** [comment]
Closing due to lack of response, but feel free to follow-up if you are still having troubles and we can reopen

**Comment by randerzander** [comment]
Yes, sorry for the late reply. On rebuilding my environment, I didn't hit the same npm error.

Thanks!

**Comment by ian-r-rose** [comment]
Thanks for following-up @randerzander !
